### ISSUE TITLE
Can't find default resource group for Lite plan

### ISSUE THREAD

**Issue by melissaw95** [IBM-Bluemix-Docs/resources#13]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
I can't find the default resource group created with my Lite Plan. I don't see any resource groups at all
2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by mekaufman** [comment]
Hi @melissaw95,

Have you tried looking for your resource group by going to the "Manage" menu in the header of the console. From the Manage menu, you can select "Account," and then select "Resource groups" from the left navigation pane. It should list your "default" resource group on that screen. Let me know if you still can't find it there.

**Comment by melissaw95** [comment]
> Hi @melissaw95,
> 
> Have you tried looking for your resource group by going to the "Manage" menu in the header of the console? From the Manage menu, you can select "Account," and then select "Resource groups" from the left navigation pane. It should list your "default" resource group on that screen. Let me know if you still can't find it there.

No that doesn't work, no matter how I get to my Resource Groups nothing shows up. No matter what I search either. It just says "Looks like you don't have any resource groups that fit that criteria. Check for correct spelling or try another search." Then when I try to create a new one it just says I can't because I'm on the Lite Plan

**Comment by mekaufman** [comment]
@melissaw95 The default resource group can be renamed. So, are you saying when you go to Manage>Account>Resource groups that there is nothing at all shown on that page? If so, you might need to open a support case because all accounts should come with 1 resource group automatically.

**Comment by melissaw95** [comment]
Ok I'll do that

**Comment by melissaw95** [comment]
But then it says I don't have the right permissions to open a support case?

**Comment by mekaufman** [comment]
@melissaw95 Are you in your own account or someone else's? If you're in someone else's account, you might not have permissions to work with the resource group or view it.

**Comment by melissaw95** [comment]
It's my account

**Comment by mekaufman** [comment]
@melissaw95 Are you an IBMer or a customer of IBM?

**Comment by melissaw95** [comment]
IBMer

**Comment by mekaufman** [comment]
@melissaw95 Can you see if you can find me on slack under @mkaufman or send me your email address and I can try and loop in the right people to get this figured out.
