### ISSUE TITLE
Service availability table is unreadable 

### ISSUE THREAD

**Issue by arlemi** [IBM-Bluemix-Docs/resources#14]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
The way the table displays the data doesn't make it easy at all to find whether a service is hosted somewhere or not

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/resources?topic=resources-services_region

3. Do you have a suggestion about how to resolve the issue?
A simple red cross for no and green check for yes would make it way easier than all this repeated text

**Comment by neal-timpe** [comment]
I hear what you're saying, @arlemi . This table is responding to specific requirements that make checkmarks impossible. If you reach out to me or someone on my team on slack or internally, we can send you a link to the work that's in development.

**Comment by mekaufman** [comment]
@arlemi Closing this issue here because we have some updates in progress internally right now. Please find me on slack or via email (mtompki@us.ibm.com) and we can discuss further and show you the work in progress.
