### ISSUE TITLE
Service Availability page is missing services and SZRs

### ISSUE THREAD

**Issue by CloudJason** [IBM-Bluemix-Docs/resources#15]
https://cloud.ibm.com/docs/resources?topic=resources-services_region#services_region%C2%A0

The page does not list all our services. For example, all of IaaS is missing, IKS is missing, etc. This looks like maybe just classical CF services. Also locations are missing. It only shows the MZRs. It does not list individual datacenters or SZRs the service might be available in.

**Comment by neal-timpe** [comment]
@CloudJason We're working on expanding the services and locations listed, and I can provide more details inside the firewall or if you ping me or someone on my team.

**Comment by mekaufman** [comment]
@CloudJason I've reached out on slack and provided our updates that are a work in progress for your review.
