### ISSUE TITLE
Dashboard Creation is spining 

### ISSUE THREAD

**Issue by Mi0drag** [IBM-Bluemix-Docs/resources#17]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?

**Comment by Mi0drag** [comment]
In the project with embedded Cognos Analytics Dashboard , creation of Dashboard is taking long time ( it is spinning forever)

**Comment by mekaufman** [comment]
Hi @Mi0drag, if the issue does not resolve, you might need to open a support case for that service. This repository is for issues with the documentation.
