### ISSUE TITLE
Service Endpoints, not Private

### ISSUE THREAD

**Issue by DRoiDonCloud** [IBM-Bluemix-Docs/resources#21]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?

The wrong terminology is used in several articles around Service Endpoints. We are not to use Private Endpoint - it's reserved for future functionality (Virtual Private Endpoint project)

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/resources?topic=resources-private-network-endpoints

3. Do you have a suggestion about how to resolve the issue?
Rename to Service Endpoint, and where we want to mention the private network centric, use private with lowercase P

**Comment by mekaufman** [comment]
I've updated this documentation based on a conversation and review with Denis.
