### ISSUE TITLE
CFEE incorrectly listed

### ISSUE THREAD

**Issue by cswanson2** [IBM-Bluemix-Docs/resources#22]
Carl Swanson - IBM Offering Manager for IBM Cloud Foundry Enterprise (CFEE)

Reproduce
- this page => https://cloud.ibm.com/docs/resources?topic=resources-services_region
- each region, scroll down to Cloud Foundry Enterprise Environment
- almost every CFEE entry is wrong

I would open a pull request, but I can't begin to imagine this is the original source for this, this should be generated somehow - I WILL do a pull request - but I suspect / think / hope this has to be fixed some other way

**Comment by mekaufman** [comment]
@cswanson2 Comment left on PR for you. Please check the service's GC record and fix there.

**Comment by mekaufman** [comment]
Fixed in GC by service team.
