### ISSUE TITLE
State the permissions/access required to create a resource group

### ISSUE THREAD

**Issue by rodalton** [IBM-Bluemix-Docs/resources#7]
We should state the permissions/access required to create a resource group in the 'Setting up your resource groups' section.

**Comment by mekaufman** [comment]
@hlucey At this time, my understanding is that only account owners can create and delete resource groups. Can you please update our best practices with this information?  You can validate that this is correct by checking with Tiffany Cross or Mark Meredith (if they don't know for sure, they should be able to point you to someone who can).
